-- ==========================================
-- CabukUlas Operational Foundation
-- Publishing workflow, verification, audit, and admin operations
-- ==========================================

ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'needs_verification',
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS data_freshness_score NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_sponsored BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS search_boost INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_publication_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_by UUID,
  ADD COLUMN IF NOT EXISTS updated_by UUID,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archived_by UUID;

ALTER TABLE contact_channels
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'needs_verification',
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS response_speed_label TEXT,
  ADD COLUMN IF NOT EXISTS source_confidence NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS last_checked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deeplink_type TEXT,
  ADD COLUMN IF NOT EXISTS created_by UUID,
  ADD COLUMN IF NOT EXISTS updated_by UUID,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archived_by UUID;

CREATE TABLE IF NOT EXISTS admin_profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  full_name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  alias TEXT NOT NULL,
  source_type TEXT DEFAULT 'manual',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID
);

CREATE TABLE IF NOT EXISTS company_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'official',
  confidence_score NUMERIC(5,2),
  checked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID
);

CREATE TABLE IF NOT EXISTS contact_channel_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_channel_id TEXT NOT NULL REFERENCES contact_channels(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  opens_at TIME,
  closes_at TIME,
  is_closed BOOLEAN NOT NULL DEFAULT false,
  timezone TEXT NOT NULL DEFAULT 'Europe/Istanbul',
  effective_from DATE,
  effective_to DATE,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS featured_placements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  placement_key TEXT NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  is_sponsored BOOLEAN NOT NULL DEFAULT false,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID,
  updated_by UUID
);

CREATE TABLE IF NOT EXISTS verification_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  check_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  result JSONB,
  checked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID
);

CREATE TABLE IF NOT EXISTS automation_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  suggestion_type TEXT NOT NULL,
  source_url TEXT,
  confidence_score NUMERIC(5,2),
  before_state JSONB,
  suggested_state JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_review',
  reviewer_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ,
  created_by UUID,
  reviewed_by UUID
);

CREATE TABLE IF NOT EXISTS content_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT REFERENCES companies(id) ON DELETE SET NULL,
  contact_channel_id TEXT REFERENCES contact_channels(id) ON DELETE SET NULL,
  report_type TEXT NOT NULL,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolved_by UUID
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  reason TEXT,
  before_state JSONB,
  after_state JSONB,
  changed_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  snapshot JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  change_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID
);

CREATE TABLE IF NOT EXISTS channel_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_channel_id TEXT NOT NULL REFERENCES contact_channels(id) ON DELETE CASCADE,
  snapshot JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  change_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID
);

CREATE INDEX IF NOT EXISTS idx_company_aliases_company_id ON company_aliases(company_id);
CREATE INDEX IF NOT EXISTS idx_company_aliases_alias_search ON company_aliases USING gin(to_tsvector('simple', alias));
CREATE INDEX IF NOT EXISTS idx_company_sources_company_id ON company_sources(company_id);
CREATE INDEX IF NOT EXISTS idx_contact_channel_hours_channel_id ON contact_channel_hours(contact_channel_id);
CREATE INDEX IF NOT EXISTS idx_featured_placements_lookup ON featured_placements(placement_key, status, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_verification_checks_entity ON verification_checks(entity_type, entity_id, status);
CREATE INDEX IF NOT EXISTS idx_automation_suggestions_status ON automation_suggestions(status, entity_type);
CREATE INDEX IF NOT EXISTS idx_content_reports_status ON content_reports(status, report_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_companies_status ON companies(status, archived_at);
CREATE INDEX IF NOT EXISTS idx_companies_featured ON companies(is_featured, is_sponsored);
CREATE INDEX IF NOT EXISTS idx_companies_verification ON companies(verification_status, verified_at);
CREATE INDEX IF NOT EXISTS idx_contact_channels_status ON contact_channels(status, archived_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_contact_channels_unique_value
  ON contact_channels(company_id, channel_type, value);
CREATE UNIQUE INDEX IF NOT EXISTS idx_contact_channels_single_fastest
  ON contact_channels(company_id)
  WHERE is_fastest = true AND archived_at IS NULL;

CREATE OR REPLACE FUNCTION has_admin_role(roles TEXT[])
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM admin_profiles
    WHERE user_id = auth.uid()
      AND is_active = true
      AND role = ANY(roles)
  );
$$;

ALTER TABLE admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_channel_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE featured_placements ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_revisions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_profiles_select_self ON admin_profiles;
CREATE POLICY admin_profiles_select_self
  ON admin_profiles FOR SELECT
  USING (user_id = auth.uid() OR has_admin_role(ARRAY['super_admin', 'admin']));

DROP POLICY IF EXISTS company_aliases_admin_select ON company_aliases;
CREATE POLICY company_aliases_admin_select
  ON company_aliases FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS company_aliases_admin_write ON company_aliases;
CREATE POLICY company_aliases_admin_write
  ON company_aliases FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor']));

DROP POLICY IF EXISTS company_sources_admin_select ON company_sources;
CREATE POLICY company_sources_admin_select
  ON company_sources FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS company_sources_admin_write ON company_sources;
CREATE POLICY company_sources_admin_write
  ON company_sources FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor']));

DROP POLICY IF EXISTS contact_channel_hours_admin_select ON contact_channel_hours;
CREATE POLICY contact_channel_hours_admin_select
  ON contact_channel_hours FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS contact_channel_hours_admin_write ON contact_channel_hours;
CREATE POLICY contact_channel_hours_admin_write
  ON contact_channel_hours FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor']));

DROP POLICY IF EXISTS featured_placements_admin_select ON featured_placements;
CREATE POLICY featured_placements_admin_select
  ON featured_placements FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS featured_placements_admin_write ON featured_placements;
CREATE POLICY featured_placements_admin_write
  ON featured_placements FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin']));

DROP POLICY IF EXISTS verification_checks_admin_select ON verification_checks;
CREATE POLICY verification_checks_admin_select
  ON verification_checks FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS verification_checks_admin_write ON verification_checks;
CREATE POLICY verification_checks_admin_write
  ON verification_checks FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

DROP POLICY IF EXISTS automation_suggestions_admin_select ON automation_suggestions;
CREATE POLICY automation_suggestions_admin_select
  ON automation_suggestions FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS automation_suggestions_admin_write ON automation_suggestions;
CREATE POLICY automation_suggestions_admin_write
  ON automation_suggestions FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

DROP POLICY IF EXISTS content_reports_admin_select ON content_reports;
CREATE POLICY content_reports_admin_select
  ON content_reports FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS content_reports_public_insert ON content_reports;
CREATE POLICY content_reports_public_insert
  ON content_reports FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS content_reports_admin_update ON content_reports;
CREATE POLICY content_reports_admin_update
  ON content_reports FOR UPDATE
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'support']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'support']));

DROP POLICY IF EXISTS audit_logs_admin_select ON audit_logs;
CREATE POLICY audit_logs_admin_select
  ON audit_logs FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS audit_logs_admin_insert ON audit_logs;
CREATE POLICY audit_logs_admin_insert
  ON audit_logs FOR INSERT
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

DROP POLICY IF EXISTS company_revisions_admin_select ON company_revisions;
CREATE POLICY company_revisions_admin_select
  ON company_revisions FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS company_revisions_admin_write ON company_revisions;
CREATE POLICY company_revisions_admin_write
  ON company_revisions FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

DROP POLICY IF EXISTS channel_revisions_admin_select ON channel_revisions;
CREATE POLICY channel_revisions_admin_select
  ON channel_revisions FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst']));

DROP POLICY IF EXISTS channel_revisions_admin_write ON channel_revisions;
CREATE POLICY channel_revisions_admin_write
  ON channel_revisions FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

CREATE OR REPLACE VIEW published_companies_public AS
SELECT *
FROM companies
WHERE status = 'published'
  AND archived_at IS NULL;

CREATE OR REPLACE VIEW published_contact_channels_public AS
SELECT *
FROM contact_channels
WHERE status = 'published'
  AND archived_at IS NULL;
