-- ==========================================
-- CabukUlas Admin + Analytics Surface
-- Public-safe projections, admin RLS, audit triggers, event store
-- ==========================================

ALTER TABLE categories
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS created_by UUID,
  ADD COLUMN IF NOT EXISTS updated_by UUID;

UPDATE companies
SET verification_status = 'needs_verification'
WHERE verification_status IS NULL OR verification_status = 'needs_review';

UPDATE contact_channels
SET verification_status = 'needs_verification'
WHERE verification_status IS NULL OR verification_status = 'needs_review';

ALTER TABLE companies
  DROP CONSTRAINT IF EXISTS companies_status_valid,
  DROP CONSTRAINT IF EXISTS companies_verification_status_valid;

ALTER TABLE companies
  ADD CONSTRAINT companies_status_valid
    CHECK (status IN ('draft', 'in_review', 'approved', 'published', 'rejected', 'archived', 'needs_verification')),
  ADD CONSTRAINT companies_verification_status_valid
    CHECK (verification_status IN ('verified', 'unverified', 'needs_verification'));

ALTER TABLE contact_channels
  DROP CONSTRAINT IF EXISTS contact_channels_status_valid,
  DROP CONSTRAINT IF EXISTS contact_channels_verification_status_valid;

ALTER TABLE contact_channels
  ADD CONSTRAINT contact_channels_status_valid
    CHECK (status IN ('draft', 'in_review', 'approved', 'published', 'rejected', 'archived', 'needs_verification')),
  ADD CONSTRAINT contact_channels_verification_status_valid
    CHECK (verification_status IN ('verified', 'unverified', 'needs_verification'));

ALTER TABLE categories
  DROP CONSTRAINT IF EXISTS categories_status_valid;

ALTER TABLE categories
  ADD CONSTRAINT categories_status_valid
    CHECK (status IN ('draft', 'published', 'archived'));

DROP TRIGGER IF EXISTS categories_updated_at ON categories;
CREATE TRIGGER categories_updated_at
  BEFORE UPDATE ON categories
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE IF NOT EXISTS product_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_pseudo_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  event_name TEXT NOT NULL,
  event_group TEXT NOT NULL DEFAULT 'public_app',
  source_screen TEXT,
  target_screen TEXT,
  company_id TEXT REFERENCES companies(id) ON DELETE SET NULL,
  category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
  contact_channel_id TEXT REFERENCES contact_channels(id) ON DELETE SET NULL,
  channel_type TEXT,
  query_text TEXT,
  query_normalized TEXT,
  platform TEXT,
  app_version TEXT,
  locale TEXT,
  device_type TEXT,
  duration_seconds NUMERIC(10,2),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_events_event_time
  ON product_events(event_name, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_events_company
  ON product_events(company_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_events_channel
  ON product_events(channel_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_events_query
  ON product_events(query_normalized, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_events_session
  ON product_events(session_id, occurred_at DESC);

ALTER TABLE product_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS product_events_public_insert ON product_events;
CREATE POLICY product_events_public_insert
  ON product_events FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS product_events_admin_select ON product_events;
CREATE POLICY product_events_admin_select
  ON product_events FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'analyst', 'support']));

DROP POLICY IF EXISTS cat_read ON categories;
DROP POLICY IF EXISTS comp_read ON companies;
DROP POLICY IF EXISTS chan_read ON contact_channels;

DROP POLICY IF EXISTS categories_public_read ON categories;
CREATE POLICY categories_public_read
  ON categories FOR SELECT
  USING (status = 'published' AND archived_at IS NULL);

DROP POLICY IF EXISTS categories_admin_read ON categories;
CREATE POLICY categories_admin_read
  ON categories FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst', 'support']));

DROP POLICY IF EXISTS categories_admin_write ON categories;
CREATE POLICY categories_admin_write
  ON categories FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor']));

DROP POLICY IF EXISTS companies_public_read ON companies;
CREATE POLICY companies_public_read
  ON companies FOR SELECT
  USING (status = 'published' AND archived_at IS NULL);

DROP POLICY IF EXISTS companies_admin_read ON companies;
CREATE POLICY companies_admin_read
  ON companies FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst', 'support']));

DROP POLICY IF EXISTS companies_admin_write ON companies;
CREATE POLICY companies_admin_write
  ON companies FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

DROP POLICY IF EXISTS contact_channels_public_read ON contact_channels;
CREATE POLICY contact_channels_public_read
  ON contact_channels FOR SELECT
  USING (status = 'published' AND archived_at IS NULL);

DROP POLICY IF EXISTS contact_channels_admin_read ON contact_channels;
CREATE POLICY contact_channels_admin_read
  ON contact_channels FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst', 'support']));

DROP POLICY IF EXISTS contact_channels_admin_write ON contact_channels;
CREATE POLICY contact_channels_admin_write
  ON contact_channels FOR ALL
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer']));

DROP POLICY IF EXISTS content_reports_admin_select ON content_reports;
CREATE POLICY content_reports_admin_select
  ON content_reports FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'editor', 'reviewer', 'analyst', 'support']));

DROP POLICY IF EXISTS content_reports_admin_update ON content_reports;
CREATE POLICY content_reports_admin_update
  ON content_reports FOR UPDATE
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'support']))
  WITH CHECK (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'support']));

DROP POLICY IF EXISTS audit_logs_admin_select ON audit_logs;
CREATE POLICY audit_logs_admin_select
  ON audit_logs FOR SELECT
  USING (has_admin_role(ARRAY['super_admin', 'admin', 'reviewer', 'analyst', 'support']));

DROP VIEW IF EXISTS published_companies_public;
CREATE VIEW published_companies_public AS
SELECT
  c.*,
  cat.name AS category_name,
  cat.icon AS category_icon,
  cat.sort_order AS category_sort_order,
  (
    SELECT ch.channel_type
    FROM contact_channels ch
    WHERE ch.company_id = c.id
      AND ch.status = 'published'
      AND ch.archived_at IS NULL
      AND ch.is_fastest = true
    ORDER BY ch.sort_order ASC, ch.updated_at DESC
    LIMIT 1
  ) AS fastest_channel_type
FROM companies c
LEFT JOIN categories cat ON cat.id = c.category_id
WHERE c.status = 'published'
  AND c.archived_at IS NULL
  AND (cat.id IS NULL OR (cat.status = 'published' AND cat.archived_at IS NULL));

DROP VIEW IF EXISTS published_contact_channels_public;
CREATE VIEW published_contact_channels_public AS
SELECT
  ch.*
FROM contact_channels ch
INNER JOIN companies c ON c.id = ch.company_id
WHERE ch.status = 'published'
  AND ch.archived_at IS NULL
  AND c.status = 'published'
  AND c.archived_at IS NULL;

CREATE OR REPLACE FUNCTION append_audit_log()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  entity_key TEXT;
  action_name TEXT;
  before_json JSONB;
  after_json JSONB;
BEGIN
  IF TG_OP = 'DELETE' THEN
    entity_key := OLD.id::TEXT;
    action_name := TG_TABLE_NAME || '_deleted';
    before_json := to_jsonb(OLD);
    after_json := NULL;
  ELSIF TG_OP = 'UPDATE' THEN
    entity_key := NEW.id::TEXT;
    action_name := TG_TABLE_NAME || '_updated';
    before_json := to_jsonb(OLD);
    after_json := to_jsonb(NEW);
  ELSE
    entity_key := NEW.id::TEXT;
    action_name := TG_TABLE_NAME || '_created';
    before_json := NULL;
    after_json := to_jsonb(NEW);
  END IF;

  INSERT INTO audit_logs (
    entity_type,
    entity_id,
    action,
    before_state,
    after_state,
    changed_by,
    created_at
  )
  VALUES (
    TG_TABLE_NAME,
    entity_key,
    action_name,
    before_json,
    after_json,
    auth.uid(),
    now()
  );

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS companies_audit_log ON companies;
CREATE TRIGGER companies_audit_log
  AFTER INSERT OR UPDATE OR DELETE ON companies
  FOR EACH ROW EXECUTE FUNCTION append_audit_log();

DROP TRIGGER IF EXISTS contact_channels_audit_log ON contact_channels;
CREATE TRIGGER contact_channels_audit_log
  AFTER INSERT OR UPDATE OR DELETE ON contact_channels
  FOR EACH ROW EXECUTE FUNCTION append_audit_log();

DROP TRIGGER IF EXISTS categories_audit_log ON categories;
CREATE TRIGGER categories_audit_log
  AFTER INSERT OR UPDATE OR DELETE ON categories
  FOR EACH ROW EXECUTE FUNCTION append_audit_log();

DROP TRIGGER IF EXISTS featured_placements_audit_log ON featured_placements;
CREATE TRIGGER featured_placements_audit_log
  AFTER INSERT OR UPDATE OR DELETE ON featured_placements
  FOR EACH ROW EXECUTE FUNCTION append_audit_log();

DROP TRIGGER IF EXISTS content_reports_audit_log ON content_reports;
CREATE TRIGGER content_reports_audit_log
  AFTER UPDATE ON content_reports
  FOR EACH ROW EXECUTE FUNCTION append_audit_log();

DROP VIEW IF EXISTS analytics_product_daily;
CREATE VIEW analytics_product_daily AS
SELECT
  date_trunc('day', occurred_at)::date AS metric_date,
  count(DISTINCT user_pseudo_id) AS unique_users,
  count(DISTINCT session_id) FILTER (WHERE event_name = 'session_started') AS sessions,
  coalesce(avg(duration_seconds) FILTER (WHERE event_name = 'session_ended'), 0)::numeric(10,2) AS average_session_seconds,
  count(*) FILTER (WHERE event_name = 'screen_view') AS screen_views,
  count(*) FILTER (WHERE event_name = 'company_opened') AS company_opens,
  count(*) FILTER (WHERE event_name IN ('contact_channel_clicked', 'cargo_tracking_clicked', 'external_link_opened')) AS channel_taps,
  count(*) FILTER (WHERE event_name = 'search_no_result') AS no_result_searches
FROM product_events
GROUP BY 1
ORDER BY 1 DESC;

DROP VIEW IF EXISTS analytics_top_companies;
CREATE VIEW analytics_top_companies AS
SELECT
  c.id AS company_id,
  c.name AS company_name,
  count(*) FILTER (WHERE pe.event_name = 'company_opened') AS opens,
  count(*) FILTER (WHERE pe.event_name = 'contact_channel_clicked') AS channel_taps
FROM product_events pe
INNER JOIN companies c ON c.id = pe.company_id
GROUP BY c.id, c.name
HAVING count(*) FILTER (WHERE pe.event_name = 'company_opened') > 0
ORDER BY opens DESC, channel_taps DESC;

DROP VIEW IF EXISTS analytics_top_channels;
CREATE VIEW analytics_top_channels AS
SELECT
  coalesce(channel_type, 'unknown') AS channel_type,
  count(*) AS taps
FROM product_events
WHERE event_name IN ('contact_channel_clicked', 'cargo_tracking_clicked', 'external_link_opened')
GROUP BY 1
ORDER BY 2 DESC;

DROP VIEW IF EXISTS analytics_no_result_searches;
CREATE VIEW analytics_no_result_searches AS
SELECT
  coalesce(nullif(query_text, ''), '(empty)') AS query_text,
  count(*) AS no_result_count
FROM product_events
WHERE event_name = 'search_no_result'
GROUP BY 1
ORDER BY 2 DESC;
